### ISSUE TITLE
Feature request: Dark mode

### ISSUE THREAD

**Issue by egasz** [Wingysam/Christmas-Community#163] opened 2024-12-11 12:39 UTC
Would it be possible to have a toggle switch (or some sort of button) in each user's profile page to have them be able to switch between dark and light mode. Or alternatively (if it's simpler) to have a single option on the admin settings page that would do the same thing, but instead of being on a per-user setting, it would be site-wide?

Thank you

**Comment by cj13579** [comment] 2024-12-12 13:29
You can do the site-wide option today by changing the theme. CC uses [bulmaswatch](https://jenil.github.io/bulmaswatch/). The default is `default`, but you can change this by setting the environment variable `BULMASWATCH`. For example, if you wanted to use the [darkly](https://jenil.github.io/bulmaswatch/darkly/) theme, you can set:

```
BULMASWATCH=darkly
```

**Comment by cj13579** [comment] 2024-12-12 13:30
This is also a duplicate of #125

**Closed** 2024-12-12 14:38 UTC
